name: flutter_tags_fork
description: Creating selectable and input tags (TextField) has never been easier.
version: 1.0.0
homepage: https://github.com/berhili098/flutter_tags_fork_fork

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
